### ISSUE TITLE
Examples list.txt

### ISSUE THREAD

**Issue by ghost** [geekysuavo/pca-utils#1]
Hi, can you put examples of files list.txt?

thanks!

**Comment by geekysuavo** [comment]
Hi Peishar,

An example file is available here: http://bionmr.unl.edu/wiki/PCA_Utilities http://bionmr.unl.edu/wiki/PCA_Utilities

Hope that helps,
~ Brad.

**Comment by ghost** [comment]
Ok, Thanks!!!

Regards
